import { createServerClient } from '@supabase/ssr'
import { cookies } from 'next/headers'
import { NextResponse } from 'next/server'
import { getAdminClient } from '@/lib/supabase/admin'
import { sendInvite } from '@/lib/email/sendInvite'

export async function POST(request: Request) {
    try {
        const { email, role, businessId } = await request.json()

        const cookieStore = await cookies()
        const supabase = createServerClient(
            process.env.NEXT_PUBLIC_SUPABASE_URL!,
            process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
            {
                cookies: {
                    getAll() {
                        return cookieStore.getAll()
                    },
                    setAll(cookiesToSet) {
                        try {
                            cookiesToSet.forEach(({ name, value, options }) =>
                                cookieStore.set(name, value, options)
                            )
                        } catch {
                            // Ignore
                        }
                    }
                }
            }
        )

        const { data: { user }, error: authError } = await supabase.auth.getUser()
        if (authError || !user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

        // Verify inviter is owner/manager
        const { data: member, error: memberError } = await supabase
            .from('business_members')
            .select('role')
            .eq('business_id', businessId)
            .eq('user_id', user.id)
            .single()

        if (memberError || (member?.role !== 'owner' && member?.role !== 'manager')) {
            return NextResponse.json({ error: 'Insufficient permissions' }, { status: 403 })
        }

        // Get business name for email
        const { data: business } = await supabase.from('businesses').select('name').eq('id', businessId).single()

        // Create invitation (token is generated by DB default)
        const adminAuthClient = getAdminClient()
        const { data: invite, error: inviteError } = await adminAuthClient
            .from('invitations')
            .insert({
                business_id: businessId,
                email,
                role,
                invited_by: user.id
            })
            .select()
            .single()

        if (inviteError) throw inviteError

        await sendInvite(email, invite.token, business?.name || 'A Business')

        return NextResponse.json({ success: true, invite })
    } catch (error: any) {
        console.error('Invite Error:', error)
        return NextResponse.json({ error: error.message }, { status: 500 })
    }
}
